import type { ComponentType } from 'react';
import * as demos from './index';

export const demoRegistry: Record<string, ComponentType> = {
  button: demos.ButtonDemo,
  textfield: demos.TextFieldDemo,
  select: demos.SelectDemo,
  checkbox: demos.CheckboxDemo,
  radio: demos.RadioDemo,
  switch: demos.SwitchDemo,
  slider: demos.SliderDemo,
  typography: demos.TypographyDemo,
  chip: demos.ChipDemo,
  badge: demos.BadgeDemo,
  avatar: demos.AvatarDemo,
  tooltip: demos.TooltipDemo,
  table: demos.TableDemo,
  card: demos.CardDemo,
  list: demos.ListDemo,
  accordion: demos.AccordionDemo,
  alert: demos.AlertDemo,
  linearprogress: demos.LinearProgressDemo,
  circularprogress: demos.CircularProgressDemo,
  snackbar: demos.SnackbarDemo,
  dialog: demos.DialogDemo,
  skeleton: demos.SkeletonDemo,
  tabs: demos.TabsDemo,
  breadcrumbs: demos.BreadcrumbsDemo,
  pagination: demos.PaginationDemo,
  stepper: demos.StepperDemo,
  menu: demos.MenuDemo,
  paper: demos.PaperDemo,
  appbar: demos.AppBarDemo,
  drawer: demos.DrawerDemo,
  container: demos.ContainerDemo,
  grid: demos.GridDemo,
  stack: demos.StackDemo,
  autocomplete: demos.AutocompleteDemo,
  rating: demos.RatingDemo,
  togglebutton: demos.ToggleButtonDemo,
  formcontrol: demos.FormControlDemo,
  inputadornment: demos.InputAdornmentDemo,
  divider: demos.DividerDemo,
  link: demos.LinkDemo,
  imagelist: demos.ImageListDemo,
  bottomnavigation: demos.BottomNavigationDemo,
  speeddial: demos.SpeedDialDemo,
  fab: demos.FabDemo,
  datepicker: demos.DatePickerDemo,
  timepicker: demos.TimePickerDemo,
  radiogroup: demos.RadioGroupDemo,
  checkboxgroup: demos.CheckboxGroupDemo,
  box: demos.BoxDemo,
  typographyvariants: demos.TypographyVariantsDemo,
};
